name: Build Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Copy JAR with commit hash
        run: |
          JAR_PATH=$(find build/libs -name '*.jar' | head -n 1)
          BASENAME=$(basename "$JAR_PATH" .jar)
          NEW_JAR="build/libs/${BASENAME}-${{ env.SHORT_SHA }}.jar"
          cp "$JAR_PATH" "$NEW_JAR"
          echo "NEW_JAR=$NEW_JAR" >> $GITHUB_ENV

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: $(basename ${{ env.NEW_JAR }})
          path: ${{ env.NEW_JAR }}
